version: '3.8'

services:
  schedule-bot:
    build: .
    ports:
      - "8000:8000"
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DATABASE_URL=sqlite:///./schedule.db
      - DEBUG=True
      - WEBAPP_URL=http://localhost:8000
    volumes:
      - ./schedule.db:/app/schedule.db
    restart: unless-stopped 